version: '2'
services:
    libellumspring-app:
        image: libellumspring
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://libellumspring-mysql:3306/libellumspring?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    libellumspring-mysql:
        extends:
            file: mysql.yml
            service: libellumspring-mysql
